<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <title>Dashboard - Base Admin</title>

        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta name="apple-mobile-web-app-capable" content="yes">    

        <link href="<?php echo $this->baseUrl ?>/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?php echo $this->baseUrl ?>/css/bootstrap-responsive.min.css" rel="stylesheet">

        <link href="<?php echo $this->baseUrl ?>/css/base-admin.css" rel="stylesheet">
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600" rel="stylesheet">

        <link href="<?php echo $this->baseUrl ?>/css/font-awesome.css" rel="stylesheet">
        <link href="<?php echo $this->baseUrl ?>/css/base-admin-responsive.css" rel="stylesheet">
        <link href="<?php echo $this->baseUrl ?>/css/pages/dashboard.css" rel="stylesheet">   
        <link href="<?php echo $this->baseUrl ?>/css/pages/faq.css" rel="stylesheet">   

        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>

    <body>

        <div class="navbar navbar-fixed-top">

            <div class="navbar-inner">

                <div class="container">

                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>

                    <a class="brand" href="./Dashboard - Base Admin_files/Dashboard - Base Admin.htm">
                        Base Admin				
                    </a>		

                    <div class="nav-collapse">
                        <ul class="nav pull-right">
                            <li class="dropdown">

                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="icon-cog"></i>
                                    Settings
                                    <b class="caret"></b>
                                </a>

                                <ul class="dropdown-menu">
                                    <li><a href="#">Account Settings</a></li>
                                    <li><a href="#">Privacy Settings</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Help</a></li>
                                </ul>

                            </li>

                            <li class="dropdown">

                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="icon-user"></i> 
                                    Rod Howard
                                    <b class="caret"></b>
                                </a>

                                <ul class="dropdown-menu">
                                    <li><a href="#">My Profile</a></li>
                                    <li><a href="#">My Groups</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Logout</a></li>
                                </ul>

                            </li>
                        </ul>

                        <form class="navbar-search pull-right">
                            <input type="text" class="search-query" placeholder="Search">
                        </form>

                    </div><!--/.nav-collapse -->	

                </div> <!-- /container -->

            </div> <!-- /navbar-inner -->

        </div> <!-- /navbar -->





        <div class="subnavbar">

            <div class="subnavbar-inner">

                <div class="container">
                    <?php
                    $partial = array('menu.phtml', 'default');
                    $this->navigation()->menu()->setPartial($partial);
                    echo $this->navigation()->menu()->render();
                    ?>
                </div>

            </div> <!-- /subnavbar-inner -->

        </div> <!-- /subnavbar -->


        <div class="main">

            <div class="main-inner">

                <div class="container">

                    <div class="row">


                        <?php echo $this->navigation()->breadcrumbs() ?>
                        <?php echo $this->layout()->content . "\n"; ?>

                        <div class="clear"></div>

                    </div> <!-- /row -->

                </div> <!-- /container -->

            </div> <!-- /main-inner -->

        </div> <!-- /main -->



        <div class="extra">

            <div class="extra-inner">

                <div class="container">

                    <div class="row">

                        <div class="span3">

                            <h4>About</h4>

                            <ul>
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Twitter</a></li>
                                <li><a href="#">Facebook</a></li>
                                <li><a href="#">Google+</a></li>
                            </ul>

                        </div> <!-- /span3 -->

                        <div class="span3">

                            <h4>Support</h4>

                            <ul>
                                <li><a href="#">Frequently Asked Questions</a></li>
                                <li><a href="#">Ask a Question</a></li>
                                <li><a href="#">Video Tutorial</a></li>
                                <li><a href="#">Feedback</a></li>
                            </ul>

                        </div> <!-- /span3 -->

                        <div class="span3">

                            <h4>Legal</h4>

                            <ul>
                                <li><a href="#">License</a></li>
                                <li><a href="#">Terms of Use</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="#">Security</a></li>
                            </ul>

                        </div> <!-- /span3 -->

                        <div class="span3">

                            <h4>Settings</h4>

                            <ul>
                                <li><a href="#">Consectetur adipisicing</a></li>
                                <li><a href="#">Eiusmod tempor </a></li>
                                <li><a href="#">Fugiat nulla pariatur</a></li>
                                <li><a href="#">Officia deserunt</a></li>
                            </ul>

                        </div> <!-- /span3 -->

                    </div> <!-- /row -->

                </div> <!-- /container -->

            </div> <!-- /extra-inner -->

        </div> <!-- /extra -->




        <div class="footer">

            <div class="footer-inner">

                <div class="container">

                    <div class="row">

                        <div class="span12">
                            © 2012 <a href="<?php echo $this->baseUrl; ?>">Zend Base</a>.
                        </div> <!-- /span12 -->

                    </div> <!-- /row -->

                </div> <!-- /container -->

            </div> <!-- /footer-inner -->

        </div> <!-- /footer -->


        <script src="<?php echo $this->baseUrl; ?>/js/jquery-1.7.2.min.js"></script>
        <script src="<?php echo $this->baseUrl; ?>/js/bootstrap.js"></script>
        <script src="<?php echo $this->baseUrl; ?>/js/base.js"></script>

        <script src="<?php echo $this->baseUrl; ?>/js/layout.js"></script>



    </body>
</html>