<html lang="en"><head>
        <meta charset="utf-8">
        <title>Login - Base Admin</title>

        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta name="apple-mobile-web-app-capable" content="yes"> 

        <link href="<?php echo $this->baseUrl ?>/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?php echo $this->baseUrl ?>/css/bootstrap-responsive.min.css" rel="stylesheet">

        <link href="<?php echo $this->baseUrl ?>/css/font-awesome.css" rel="stylesheet">
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600" rel="stylesheet">
        <link href="<?php echo $this->baseUrl ?>/css/base-admin.css" rel="stylesheet">

        <link href="<?php echo $this->baseUrl ?>/css/pages/signin.css" rel="stylesheet" type="text/css">     
        
    </head>

    <body>

        <div class="navbar navbar-fixed-top">

            <div class="navbar-inner">

                <div class="container">

                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>

                    <a class="brand" href="./">
                        Base Admin				
                    </a>		

                    <div class="nav-collapse">
                        <ul class="nav pull-right">

                            <li class="">						
                                <a href="./signup.html" class="">
                                    Create an Account
                                </a>

                            </li>

                            <li class="">						
                                <a href="./" class="">
                                    <i class="icon-chevron-left"></i>
                                    Back to Homepage
                                </a>

                            </li>
                        </ul>

                    </div><!--/.nav-collapse -->	

                </div> <!-- /container -->

            </div> <!-- /navbar-inner -->

        </div> <!-- /navbar -->



        <div class="account-container">

            <div class="content clearfix">

                <form action="./" method="post">

                    <h1>Sign In</h1>		

                    <div class="login-fields">

                        <p>Entre usando sua conta registrada:</p>

                        <div class="field">
                            <label for="username">Login:</label>
                            <input type="text" id="username" name="username" value="" placeholder="Username" class="login username-field">
                        </div> <!-- /field -->

                        <div class="field">
                            <label for="password">Senha:</label>
                            <input type="password" id="password" name="password" value="" placeholder="Password" class="login password-field">
                        </div> <!-- /password -->

                    </div> <!-- /login-fields -->

                    <div class="login-actions">

                        <span class="login-checkbox">
                            <input id="Field" name="Field" type="checkbox" class="field login-checkbox" value="First Choice" tabindex="4">
                            <label class="choice" for="Field">Manter Logado</label>
                        </span>

                        <button class="button btn btn-warning btn-large">Entrar</button>

                    </div> <!-- .actions -->

                </form>

            </div> <!-- /content -->

        </div> <!-- /account-container -->


        <!-- Text Under Box -->
        <div class="login-extra">
            Não tem conta? <a href="./signup.html">Cadastrar</a><br>
            Esqueci minha <a href="#">Senha</a>
        </div> <!-- /login-extra -->
        ]

        <script src="<?php echo $this->baseUrl; ?>/js/jquery-1.7.2.min.js"></script>
        <script src="<?php echo $this->baseUrl; ?>/js/bootstrap.js"></script>
        <script src="<?php echo $this->baseUrl; ?>/js/signin.js"></script>


    </body><span id="skype_highlighting_settings" display="none" autoextractnumbers="1"></span><object id="skype_plugin_object" location.href="http://wbpreview.com/previews/WB00U99JJ/login.html" location.hostname="wbpreview.com" style="position: absolute; visibility: hidden; left: -100px; top: -100px; " width="0" height="0" type="application/x-vnd.skype.click2call.chrome.5.7.0"></object></html>